coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default: true
    patch:
      default: off
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "build-settings/*.js"
  - "utils/*.js"
  - "packages/**/dist/index.js"
  - "packages/**/types/**/*.ts"
  - "packages/**/examples/**/*.ts"
